# Generated by Django 2.1 on 2019-12-05 04:59

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191205_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=3000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default=blog.models.get_first_category, related_name='posts', to='blog.Category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='adresses',
            field=models.TextField(verbose_name='список адресов'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='date_of_off',
            field=models.DateTimeField(verbose_name='дата отключения'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='date_of_on',
            field=models.DateTimeField(verbose_name='дата подачи'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='reason',
            field=models.CharField(max_length=50, verbose_name='причина отключения'),
        ),
    ]
