# Generated by Django 2.1 on 2019-12-12 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191213_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 8, 49, 53, 994221), verbose_name='дата публикации'),
        ),
    ]
