# Generated by Django 2.1 on 2019-12-22 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20191223_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 1, 50, 51, 799726), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='date_of_off',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 1, 50, 51, 818441), verbose_name='дата отключения'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='date_of_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 1, 50, 51, 818441), verbose_name='дата подачи'),
        ),
    ]
