# Generated by Django 3.1.2 on 2020-10-07 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20201008_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 10, 50, 46, 435490), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='date_of_off',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 10, 50, 46, 455492), verbose_name='дата отключения'),
        ),
        migrations.AlterField(
            model_name='wateroff',
            name='date_of_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 10, 50, 46, 455492), verbose_name='дата подачи'),
        ),
    ]
